port: "47777"

# main logic (app)
# -----------------------------------------------

update_rooms:
  timeout: 16ms

room:
  max_profile_count: 6

found_game:
  chatting_stage_duration: 30m
  choosing_stage_duration: 15s

background:
  update_rooms:
    with_searching_state:
      interval_from_last_update_to_next_state: 10s

# -----------------------------------------------

# TODO: add timeout process request
control_server:
  token:
    duration: 5m
    secret: "your_secret"

debug_server:
  launch: true

# -----------------------------------------------

storage:
  type: "sqlite"
  sql:
    initialization_timeout: 5s
    
    sqlite:
      directory: "../storage/"
      file: "storage.db"

    postgre:
    # ...

  memory:
  # ...

  default_admin_entry:
    login: "admin"
    pass: "admin"

